# Generated by Django 5.2.17 on 2026-08-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_commercial_order_commercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rotation commerciale',
                'verbose_name_plural': 'Rotation commerciale',
            },
        ),
        migrations.AddField(
            model_name='commercial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
