# Generated by Django 5.2.17 on 2026-08-19 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_commercialrotation_commercial_updated_at'),
        ('products', '0003_productrange_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Article de commande', 'verbose_name_plural': 'Articles de commande'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productrange'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('product_range__isnull', True)), models.Q(('product__isnull', True), ('product_range__isnull', False)), _connector='OR'), name='order_item_one_type_only'),
        ),
    ]
