# Generated by Django 5.2.17 on 2026-08-14 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productrange_category_slug_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrange',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
